# =============================================================================
# 21  Supplementary Tables workbook
#
# Combines Supplementary Tables 1-15 (CSV) into one .xlsx: a table of contents
# plus one tab per table, each with its legend above the data. Tables 1-13 are
# read from Supplementary_Tables/; Tables 14 and 15 are the outputs of
# 21_chenComparison and 22_chenPipeline, read where those scripts write them.
#
# Run:     Rscript 21_supplementaryWorkbook.R    (after every table is built)
# Output:  Writing/Submission/Supplementary_Tables.xlsx
# =============================================================================

.a <- commandArgs(FALSE); .f <- sub('^--file=', '', .a[grep('^--file=', .a)])
source(file.path(if (length(.f)) dirname(normalizePath(.f)) else '.', '00_config.R'))
library(openxlsx)

OUT <- paste0(SUBMISSION, 'Supplementary_Tables.xlsx')

TABLES <- tibble::tribble(
  ~tab, ~file, ~legend,
  'S1_HarmonicGenes', 'SupTable_1_HarmonicGenes.csv',
  'Supplementary Table 1. Rhythmic genes identified across GTEx v10 tissues. One row per gene-tissue pair that passed the rhythmicity test (Bonferroni-adjusted likelihood ratio test p < 0.05; n = 4,033 pairs), comparing the harmonic (cosinor) model with the linear model. The Bonferroni correction is applied within tissue, over the genes tested in that tissue; 1,285,139 gene-tissue pairs were tested across 50 tissues. 49 of those 50 tissues contribute at least one rhythmic gene, Cells Cultured fibroblasts contributing none. Columns: term, fitted model; X.Df, model degrees of freedom; LogLik, log-likelihood; df, difference in degrees of freedom between models; statistic, chi-square LRT statistic; p.value, raw LRT p-value; gene, Ensembl gene ID; hgnc_symbol, gene symbol, falling back to the Ensembl gene ID where Ensembl assigns no symbol (resolved from the Ensembl REST lookup endpoint by Code/03_geneSymbolMap.R and cached in Data/ref/annot/ensembl_hgnc_map.csv); tissue, GTEx tissue; p.adj, Bonferroni-adjusted p-value, equal to p.value multiplied by the number of genes tested in that tissue.',
  'S2_cdEQTL', 'SupTable_2_cdEQTL.csv',
  'Supplementary Table 2. All 168 significant cd-eQTL. One row per gene-variant-tissue association passing the interaction-model likelihood ratio test (raw p < 1e-4). Columns: term, fitted interaction model; X.Df, model degrees of freedom; LogLik, log-likelihood; df, difference in degrees of freedom; statistic, chi-square LRT statistic; p.value, raw interaction LRT p-value; gene, Ensembl gene ID; variant, lead SNP; tissue, GTEx tissue; p.adj, adjusted p-value; geneModif, Ensembl gene ID without version suffix; hgnc_symbol, gene symbol, falling back to the Ensembl gene ID where Ensembl assigns no symbol.',
  'S3_cdEQTL_54independent', 'SupTable_3_cdEQTL_54independent.csv',
  'Supplementary Table 3. The 54 independent cd-eQTL obtained after LD pruning (pairwise r2 < 0.1; lead variant retained), associated with 51 genes across 28 tissues. Columns as in Table 2.',
  'S4_cdEQTL_coefficients', 'SupTable_4_cdEQTL_coefficients.csv',
  'Supplementary Table 4. Interaction-model regression coefficients for every significant cd-eQTL. One row per fitted coefficient (n = 4,004 rows across 167 associations), giving the full harmonic interaction model underlying the likelihood ratio tests reported in Table 2. Columns: gene, Ensembl gene ID; hgnc_symbol, gene symbol, falling back to the Ensembl gene ID where Ensembl assigns no symbol; variant, lead SNP; tissue, GTEx tissue; term, model term; estimate, fitted coefficient; std.error; statistic, t statistic; p.value. Terms appear in fitted order: intercept; the variant, named by its rsID and coded as the number of alternate allele copies; the technical covariates sex, platform, pcr, PC1-5 and InferredCov1-10; the cosinor terms sin(radian) and cos(radian); and the genotype-by-time interaction terms rsID:sin(radian) and rsID:cos(radian), whose joint significance defines the cd-eQTL. Genotype-group amplitude is sqrt((b_sin + g*b_variant:sin)^2 + (b_cos + g*b_variant:cos)^2) for g copies of the alternate allele. Four associations in single-sex tissues (Ovary, Testis, Vagina) have 23 rather than 24 coefficients, as sex is constant and dropped from the fit.',
  'S5_dryRvalidation', 'SupTable_5_dryRvalidation.csv',
  'Supplementary Table 5. dryR validation of the 54 independent cd-eQTL. Each locus was re-fitted with dryR on the same covariate-residualised expression used for the cosinor parameter tests, with genotype dosage as the condition and CHIRAL-inferred internal phase as time. dryR fits every candidate rhythm model (5 for two genotype groups, 15 for three) and selects one by Bayesian information criterion (BIC) weight, with no significance threshold. dryR selects a model in which rhythmicity is not shared between genotype groups at 51 of 54 loci (94.4%); at the remaining 3, ZFYVE28 (Brain Cortex), DBP (Nerve Tibial) and ENSG00000236266 (Ovary), it selects one rhythm shared by all genotype groups. The full BIC weight profile of every locus is shown in Supplementary Figure 1. Columns: gene, Ensembl gene ID; hgnc_symbol, gene symbol, falling back to the Ensembl gene ID where Ensembl assigns no symbol; variant, lead SNP; tissue, GTEx tissue; n, donors entering the dryR fit; n_genotype_groups and genotype_groups, the dosage groups retained at n >= 10 (0 = homozygous reference, 1 = heterozygous, 2 = homozygous alternate); regression_LRT_statistic, regression_LRT_p.value and regression_LRT_p.adj, the chi-square statistic, raw p-value and adjusted p-value of the genotype-by-time interaction likelihood ratio test from the harmonic regression model, carried over from Table 3 and not produced by dryR; dryR_chosen_model, the BIC-selected model index, decoded against the number of groups since the same integer denotes different models for 2 and 3 groups; dryR_model_desc, that model in words, where groups written together share one rhythm and a group with no cosinor term is flat; dryR_model_BICW, the BIC weight of the selected model among the 5 or 15 candidates; concordance, discordant where the selected model is one rhythm shared by all genotype groups (no genotype effect on rhythmicity), concordant otherwise.',
  'S6_cdEQTL_classification', 'SupTable_6_cdEQTL_classification.csv',
  "Supplementary Table 6. Classification of the effect of each of the 54 independent cd-eQTL (Supplementary Table 3) on the amplitude and the acrophase of the rhythm. For every locus a separate cosinor was fitted to each genotype group on covariate-residualised expression, and amplitudes and acrophases were compared across groups with the F-tests of Bingham et al. (1982); genotype groups with fewer than 10 donors were not fitted. Adjusted p-values are Benjamini-Hochberg over the 54 loci, separately for each parameter. These tests describe which rhythmic parameter carries the genetic effect and do not re-assess the association itself, which was established by the interaction likelihood ratio test (Supplementary Table 2). A locus is classified as 'both' if both adjusted p-values are < 0.1, 'amplitude' or 'phase' if only that one is; when neither passes, the locus is assigned to the parameter with the smaller adjusted p-value. Because an acrophase is only defined for a rhythmic group, a phase call further requires at least two genotype groups whose amplitude differs from zero (Bingham zero-amplitude test); phase loci failing this requirement are classified as 'undetermined'. All loci classified as 'both' meet it. Counts: 28 amplitude (5 CCG, 23 CRG), 13 phase (0 CCG, 13 CRG), 10 both (3 CCG, 7 CRG), 3 undetermined (0 CCG, 3 CRG). Columns: gene, Ensembl gene ID; hgnc_symbol, gene symbol, falling back to the Ensembl gene ID where Ensembl assigns no symbol; variant, lead SNP; tissue, GTEx tissue; gene_type, CCG (core circadian gene) or CRG (circadian regulated gene); n_genotype_groups, number of genotype dosage groups fitted; group_sizes, donors per group, in dosage order 0/1/2; F_amplitude, p_amplitude and padj_amplitude, the F statistic, raw and adjusted p-value of the test of equal amplitude; F_acrophase, p_acrophase and padj_acrophase, the same for the test of equal acrophase; df_num and df_denom, the F-test degrees of freedom; classification, amplitude, phase, both or undetermined; assigned_by, FDR when at least one adjusted p-value is < 0.1, smaller adjusted p otherwise; zeroAmp_p_by_group, p-value of the Bingham test that the amplitude of each genotype group is zero, as dosage:p; n_groups_nonzero_amplitude, number of groups whose amplitude differs from zero (95% confidence region excluding the origin).",
  'S7_BMAL1_amplitude', 'SupTable_7_BMAL1_amplitude.csv',
  'Supplementary Table 7. Oscillation amplitude of BMAL1 (variant rs11022718) by tissue and genotype group, across the 49 tissues with at least one rhythmic gene. From a separate cosinor fitted to each genotype group on covariate-residualised expression, the model used for the amplitude and acrophase tests (Supplementary Table 6) and shown in Figure 2b and Figure 3a-b; genotype groups with fewer than 10 donors were not fitted. Columns: gene, Ensembl gene ID; hgnc_symbol, gene symbol; tissue; variant; genotype, number of copies of the rs11022718-T allele; n, donors in the genotype group; amplitude, sqrt(sin^2 + cos^2) of the fitted cosinor coefficients.',
  'S8_BMAL1_phase', 'SupTable_8_BMAL1_phase.csv',
  'Supplementary Table 8. Acrophase of BMAL1 (variant rs11022718) by tissue and genotype group, across the 49 tissues with at least one rhythmic gene. From a separate cosinor fitted to each genotype group on covariate-residualised expression, the model used for the amplitude and acrophase tests (Supplementary Table 6) and shown in Figure 2b and Figure 3a-b; genotype groups with fewer than 10 donors were not fitted. Columns: gene, Ensembl gene ID; hgnc_symbol, gene symbol; tissue; variant; genotype, number of copies of the rs11022718-T allele; n, donors in the genotype group; phase, time of peak expression in hours (0-24) on the CHIRAL-inferred internal time scale, atan2(sin, cos) of the fitted cosinor coefficients.',
  'S9_TMED10_amplitude', 'SupTable_9_TMED10_amplitude.csv',
  'Supplementary Table 9. Oscillation amplitude of TMED10 (variant rs76379942) by tissue and genotype group. Computed as in Table 7; the genotype column counts copies of the rs76379942 deletion allele (AG>A). Columns as in Table 7.',
  'S10_TMED10_phase', 'SupTable_10_TMED10_phase.csv',
  'Supplementary Table 10. Acrophase of TMED10 (variant rs76379942) by tissue and genotype group. Computed as in Table 8; the genotype column counts copies of the rs76379942 deletion allele (AG>A). Columns as in Table 8.',
  'S11_BMAL1_cosineSimilarity', 'SupTable_11_BMAL1_cosineSimilarity.csv',
  'Supplementary Table 11. Pairwise tissue-by-tissue cosine similarity of the rs11022718 effect on BMAL1, computed from the four estimated rhythmic parameters (sin, cos, and their genotype interaction terms). The first two columns give the gene identity (gene, Ensembl gene ID; hgnc_symbol, gene symbol), constant down the table, and the third column is the reference tissue; the remaining 49 columns form the 49 x 49 similarity matrix. A value of 1 indicates an identical effect, -1 an opposite effect, and 0 an orthogonal effect.',
  'S12_TMED10_cosineSimilarity', 'SupTable_12_TMED10_cosineSimilarity.csv',
  'Supplementary Table 12. Pairwise tissue-by-tissue cosine similarity of the rs76379942 effect on TMED10, computed as in Table 11. Columns as in Table 11: gene and hgnc_symbol, then the reference tissue, then the 49 x 49 similarity matrix.',
  'S13_PheWAS', 'SupTable_13_PheWAS.csv',
  'Supplementary Table 13. Significant cd-eQTL-phenotype associations from the Pan-UK Biobank PheWAS (European ancestry). One row per variant-phenotype pair passing p < 4.6e-5 (n = 310 associations spanning 100 distinct phenotypes, 34 variants and 32 genes). The first two columns give the cd-eQTL gene the variant was discovered for (gene, Ensembl gene ID; hgnc_symbol, gene symbol), joined on rsID; every row maps to exactly one gene, spanning 32 genes across the 34 variants. The remaining columns follow the Pan-UK Biobank GWAS manifest; key fields: variant, chromosome:position:reference:alternate; neglog10_pval_EUR, -log10 p-value in Europeans; description / category / phewasClass, phenotype annotation; rsID, dbSNP identifier.',
  'S14_ChenSharedRhyQTL', paste0(CHEN_DIR, 'chenComparison/chen_cdeQTL_merged.csv'),
  'Supplementary Table 14. Rhythmic QTLs (rhyQTLs) reported by Chen et al. (ref. 24) that were also tested by the interaction model. Chen et al. Supplementary Data 2 lists their significant rhyQTLs, one row per variant-gene pair and tissue (GTEx v8, cis-window +/- 1 Mb). Rows were restricted to variants within +/- 50 kb of the gene TSS (GTEx v10 annotation), mapped to rsIDs by chromosome, position and alleles, and kept when the same gene-variant pair was tested in the same tissue by the cd-eQTL scan, that is, the gene was rhythmic in that tissue and heterozygotes made up at least 10% of donors (n = 4,513 rows, 43 tissues). Columns prefixed chen_ are copied from Chen et al.; columns prefixed cdeQTL are from this study. Columns: tissue, GTEx tissue; gene_id, Ensembl gene ID; gene_name, gene symbol; rsID; gtex_variant_id; chr, Position, REF and ALT, variant position (GRCh38) and alleles as reported by Chen et al.; allele_match, whether REF and ALT matched the GTEx lookup table directly or after swapping; distance_to_TSS, in bp; chen_ID and chen_rhyGene.ID, Chen et al. variant and gene identifiers; chen_Sample.size.0, chen_Sample.size.1 and chen_Sample.size.2, genotype-group sizes sorted from largest to smallest (not genotype dosage); chen_pval_0, chen_phase_0 and chen_amp_0, cosinor p-value, acrophase (hours) and peak-to-trough amplitude (log2) of the largest genotype group; chen_pval_1, chen_phase_1 and chen_amp_1, the same for the second-largest group; chen_Chosen.model, dryR model chosen most often over 20 downsampled fits (1, no rhythm in either group; 2 and 3, rhythm in one group only; 4, the same rhythm in both groups; 5, different rhythms); chen_G.test_pval, G-test p-value of the model counts; chen_pval, reported HANOVA p-value; chen_first_failed, first of the criteria of Chen et al. that the row fails when re-applied to these reported values, nothing refitted; cdeQTL_LRT_statistic, cdeQTL_p and cdeQTL_p.adj_BH, chi-square statistic, raw p-value and within-tissue Benjamini-Hochberg adjusted p-value of the genotype-by-time interaction likelihood ratio test; cdeQTL, TRUE when the raw p-value is < 1e-4.',
  'S15_ChenPipeline54', paste0(CHEN_DIR, 'chenPipeline/chenPipeline_54cdeQTL.csv'),
  'Supplementary Table 15. The rhyQTL calling pipeline of Chen et al. (ref. 24) re-implemented on GTEx v10 and applied to the 54 independent cd-eQTL (Supplementary Table 3). Steps follow their code (github.com/YingChen10/rhyQTL, scripts 0_0 to 0_5): step 0, at least two genotype groups of >= 50 donors; step 1, cosinor in each of the two largest genotype groups, at least one with p < 0.01 and peak-to-trough amplitude > log2(1.5); step 2, dryR on the two groups after downsampling the larger to the size of the smaller, rejected when the chosen model is 1 (no rhythm in either group) or 4 (the same rhythm in both); step 3, dryR repeated on 20 downsamplings, G-test p < 0.05 on the counts of the chosen models; step 4, HANOVA between the two groups; step 5, cosinor p < 5e-4 in the group with the larger amplitude, G-test p < 0.05 and HANOVA p < 0.05. Differences from Chen et al.: expression is GTEx v10 normalised expression residualised on the covariates used in this study, not log2 CPM, so the amplitude threshold is applied on a different scale; time is the CHIRAL donor inferred phase; HANOVA is run without dividing each group by its mean (norm = FALSE), which is undefined for residuals centred on 0; the HANOVA p-value is raw, as their Benjamini-Hochberg correction over all tests of a tissue cannot be reproduced for 54 loci, so the call is an upper bound on what their pipeline would report; step 2, a single random draw in Chen et al., is repeated 100 times and passes when at least half of the draws select model 2, 3 or 5; genotypes are dosages from GTEx v9 whole genome sequencing. Columns: gene, Ensembl gene ID; variant; tissue, GTEx tissue; hgnc_symbol, gene symbol; n_0, n_1 and n_2, donors with 0, 1 and 2 copies of the alternate allele; group_large and group_second, dosage of the largest and second-largest genotype group; step0_size, step 0 passed; pval_0, phase_0 and amp_0, cosinor p-value, acrophase (hours) and peak-to-trough amplitude of the largest group; pval_1, phase_1 and amp_1, the same for the second-largest group; step1_pval and step1_amp, the two step 1 criteria; pval_maxAmp, cosinor p-value of the group with the larger amplitude; dryR_once_model and step2_dryR_once, model chosen and pass for a single step 2 draw, as in Chen et al.; step2_n_fit, step 2 draws that converged; step2_pass_rate, step2_model1_rate and step2_model4_rate, fraction of those draws passing, choosing model 1 and choosing model 4; step2_dryR, step 2 passed (pass rate >= 0.5); gtest_p, gtest_model and gtest_times, G-test p-value, most frequent model and its count over the 20 draws; step3_gtest, step 3 passed; hanova_p, raw HANOVA p-value; cdeQTL_p, raw interaction likelihood ratio test p-value from Supplementary Table 3; step5_rhythm, pval_maxAmp < 5e-4; rhyQTL, all steps passed; rhyQTL_noAmpFilter, all steps passed without the step 1 amplitude criterion; first_failed, first step the locus fails.')

headerStyle <- createStyle(fgFill = '#1F4E78', fontColour = '#FFFFFF', textDecoration = 'bold', fontSize = 10)
legendStyle <- createStyle(wrapText = TRUE, valign = 'top', fontSize = 10)

wb <- createWorkbook()
addWorksheet(wb, 'TOC')
writeData(wb, 'TOC', 'Supplementary Tables - Table of Contents', startRow = 1)
addStyle(wb, 'TOC', createStyle(textDecoration = 'bold', fontSize = 14), rows = 1, cols = 1)

toc <- data.frame(Tab = TABLES$tab, Table = sub('\\..*', '', TABLES$legend),
                  Description = sub('^[^.]*\\. ', '', TABLES$legend), `Data rows` = NA_integer_,
                  check.names = FALSE)
TABLES$path <- ifelse(startsWith(TABLES$file, '/'), TABLES$file, paste0(TABLE_DIR, TABLES$file))
for (k in seq_len(nrow(TABLES))) {
  d  <- fread(TABLES$path[k])
  sh <- TABLES$tab[k]
  toc$`Data rows`[k] <- nrow(d)
  addWorksheet(wb, sh)
  writeData(wb, sh, TABLES$legend[k], startRow = 1)
  mergeCells(wb, sh, cols = 1:min(ncol(d), 12), rows = 1)
  addStyle(wb, sh, legendStyle, rows = 1, cols = 1)
  setRowHeights(wb, sh, rows = 1, heights = 75)
  writeData(wb, sh, d, startRow = 3, headerStyle = headerStyle)
  freezePane(wb, sh, firstActiveRow = 4)
  setColWidths(wb, sh, cols = seq_len(ncol(d)),
               widths = pmin(pmax(nchar(names(d)) + 2, 9,
                                  vapply(head(d, 60), function(x) max(nchar(as.character(x)), 0,
                                                                      na.rm = TRUE), numeric(1)) + 2), 40))
}
writeData(wb, 'TOC', toc, startRow = 3, headerStyle = headerStyle)
for (k in seq_len(nrow(TABLES)))
  writeFormula(wb, 'TOC', startRow = 3 + k, startCol = 1,
               x = makeHyperlinkString(sheet = TABLES$tab[k], row = 1, col = 1, text = TABLES$tab[k]))
addStyle(wb, 'TOC', createStyle(wrapText = TRUE, valign = 'top'),
         rows = 4:(3 + nrow(TABLES)), cols = 3, gridExpand = TRUE)
setColWidths(wb, 'TOC', cols = 1:4, widths = c(28, 34, 90, 11))
freezePane(wb, 'TOC', firstActiveRow = 4)

saveWorkbook(wb, OUT, overwrite = TRUE)
message('Wrote ', OUT)
